apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sc-hello-app
  annotations:
    github.com/project-slug: sujanthakare/sc-hello-app
spec:
  type: other
  lifecycle: unknown
  owner: sujanthakare